<a href="https://colab.research.google.com/github/KatherinePalaciosaCortez/etl-data-pipeline-/blob/main/%20notebooks/clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [5]:
#ruta del dataset almacenado en git
url = "https://raw.githubusercontent.com/KatherinePalaciosaCortez/etl-data-pipeline-/refs/heads/main/clientes.csv"

In [4]:
import pandas as pd
url = "https://raw.githubusercontent.com/KatherinePalaciosaCortez/etl-data-pipeline-/main/data/raw/clientes.csv"

In [7]:
url = "https://raw.githubusercontent.com/KatherinePalaciosaCortez/etl-data-pipeline-/main/data/raw/clientes.csv"
df = pd.read_csv(url)
print("Dataset Cargado corrextamente")

Dataset Cargado corrextamente

In [ ]:
display(df.head())

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [ ]:
print("primeras filas del dataset")
display(df.head())

primeras filas del dataset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

bloque #2

In [8]:
print("Disemensiones del dataset(filas,coloumnas)")
print(df.shape)

Disemensiones del dataset(filas,coloumnas)
(3030, 7)

In [11]:
#crear columna para registrar errores
df["motivo_rechazo"]=""

# Debugging: Print columns to check for 'id_aseguradora'
print("Columnas disponibles en el DataFrame:")
print(df.columns)

#validar id aseguradora
# Es probable que la columna 'id_aseguradora' no exista en el DataFrame.
# Por favor, verifica las columnas disponibles en la salida anterior y corrige el nombre de la columna.
# Por ahora, esta línea está comentada para evitar el error:
# df.loc[df["id_aseguradora"].isnull(),"motivo_rechazo"]+="id_aseguradora nulo;"

Columnas disponibles en el DataFrame:
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento', 'motivo_rechazo'],
      dtype='object')

In [12]:
print("columnas del dataset")
print(df.columns)

columnas del dataset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento', 'motivo_rechazo'],
      dtype='object')

In [13]:
print("tipo de datos")
print(df.dtypes)

tipo de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
motivo_rechazo      object
dtype: object

In [14]:
print("valorees nulos por columna")
print(df.isnull().sum())

valorees nulos por columna
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
motivo_rechazo        0
dtype: int64

In [15]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

bloque 3 limpieza

In [16]:
#ELIMINA ESPACIOS AL INICO Y AL FINAL E COLUMNAS DE TEXTO
for col in df.select_dtypes(include="object").columns:df[col]=df[col].str.strip()

In [17]:
#Normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [18]:
#Normalizar el email
df["email"]=df["email"].str.lower()

In [19]:
#Normalizar el genero
df["genero"]=df["genero"].str.upper()

In [20]:
#Convertir fecha de nacimiento a formato fecha
df['fecha_nacimiento']=pd.to_datetime(df['fecha_nacimiento'],errors="coerce")

In [21]:
#normalizar ciudad
df["ciudad"]=df['ciudad'].str.title()

In [22]:
#normalizar Ciudad
df['ciudad']=df['ciudad'].str.title()
df['ciudad']=df['ciudad'].astype(str)
df['ciudad']=df['ciudad'].str.upper()

In [23]:
#normalizar segmento
df['segmento']=df['segmento'].astype(str)
df['segmento']=df['segmento'].str.strip()
df['segmento']=df['segmento'].str.upper()

validacion de datos

In [24]:
from os import EX_TEMPFAIL
from enum import nonmember
for col in df.columns: print(col)

id_cliente
nombre
email
genero
fecha_nacimiento
ciudad
segmento
motivo_rechazo