<a href="https://colab.research.google.com/github/KatherinePalaciosaCortez/etl-data-pipeline-/blob/main/%20notebooks/siniestros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/darkeyr0728/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"

df = pd.read_csv(url)

df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [4]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

In [5]:
#Limpieza de datos

siniestros = df.copy()

siniestros.columns = siniestros.columns.str.strip().str.lower()

for col in siniestros.select_dtypes(include='object').columns:
    siniestros[col] = siniestros[col].astype(str).str.strip()

siniestros = siniestros.replace(r'^\s*$', pd.NA, regex=True)

df['fecha_siniestro'] = pd.to_datetime(df['fecha_siniestro'], errors='coerce')

df['monto_siniestro'] = (
    df['monto_siniestro']
    .astype(str)
    .str.replace(r'[^0-9.]', '', regex=True)

)


df['monto_siniestro'] = pd.to_numeric(df['monto_siniestro'], errors='coerce')
df['estado'] = df['estado'].fillna('Desconocido')
df['estado'] = df['estado'].str.strip().str.lower()

siniestros = siniestros.drop_duplicates()

/tmp/ipykernel_2946/2427842244.py:12: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['fecha_siniestro'] = pd.to_datetime(df['fecha_siniestro'], errors='coerce')

In [9]:


#Separar datos validos
validos = siniestros[
    siniestros['id_poliza'].notna() &
    siniestros['estado'].notna()
].copy()

rechazados = siniestros[
    siniestros['id_poliza'].isna() |
    siniestros['estado'].isna()
].copy()

In [10]:
#Motivo de Rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['id_poliza']):
        motivos.append("id_poliza_vacio")

    if pd.isna(row['estado']):
        motivos.append("estado_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [11]:
#Conectar con Postgress
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_d64b_user:p6QnZIQqgOGUKctlfJR0R166FJ7kgt51@dpg-d6qu9dfgi27c73aabfog-a.oregon-postgres.render.com/etl_seguros_d64b"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 40.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [12]:
#Cargar Datos Postgress

validos.to_sql(
    'siniestros_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'siniestros_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [13]:
#Validar la carga
pd.read_sql(
"SELECT * FROM siniestros_curated ",
engine
)

      id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0                1      17400      16-10-2025         2092.59    ABIERTO
1                2       2465      01/08/2025        7,076.25    Abierto
2                3      15785      19-09-2025          702.27    cerrado
3                4      14299      27/09/2025          274.63    Abierto
4                5      12908      01/12/2025        9,377.69  Rechazado
...            ...        ...             ...             ...        ...
4615          4616      12223      2025/09/19         5806.47        nan
4616          4617       3953        06-27-25        14622.50    Cerrado
4617          4618      10239        10-26-25             nan    ABIERTO
4618          4619      18897      2025-12-29          354.26        nan
4619          4620      10815      11-10-2025        14958.46    ABIERTO

[4620 rows x 5 columns]

In [17]:
siniestros_curated_df = pd.read_sql("SELECT * FROM siniestros_curated", engine)
siniestros_curated_df.to_csv('siniestros_curated.csv', index=False)

In [22]:
from google.colab import files

files.download('siniestros_rejects.csv')